### ISSUE TITLE
Search Api error

### ISSUE THREAD

**Issue by rkratky** [nick42d/youtui#128]
When trying to search, no results are returned, and this error is returned:
```
$ youtui -d search-artists beatles
Api error <Key /contents/tabbedSearchResultsRenderer/tabs/0/tabRenderer/content/sectionListRenderer/contents/0/musicShelfRenderer/contents not found in Api response.>
```
Doing the same in the TUI returns a bit more in the logs (though I can't select the text as the program tries to capture the mouse event, so adding a screenshot):

![image](https://github.com/user-attachments/assets/9e2080b2-f910-41d6-8074-76bd0224284e)

**Comment by rkratky** [comment]
So, it's not limited to searches. For example:
```
$ youtui get-library-playlists
[
    Playlist {
        playlist_id: PlaylistID(
            "VLLM",
        ),
        title: "Liked Music",
        thumbnails: [
            Thumbnail {
                height: 192,
                width: 192,
                url: "https://www.gstatic.com/youtube/media/ytm/images/pbg/liked-music-@192.png",
            },
            Thumbnail {
                height: 576,
                width: 576,
                url: "https://www.gstatic.com/youtube/media/ytm/images/pbg/liked-music-@576.png",
            },
        ],
        count: None,
        description: Some(
            "Auto playlist",
        ),
        author: None,
    },

[snip]
```

```
$ youtui get-playlist VLLM
Api error <Key /contents/twoColumnBrowseResultsRenderer/tabs/0/tabRenderer/content/sectionListRenderer/contents/0/musicResponsiveHeaderRenderer/secondSubtitle/runs/4/text not found in Api response.>
```

**Comment by nick42d** [comment]
G'day, sorry to hear this is occurring. Unfortunately I haven't done a great job of implementing logging yet, so will need some assistance from you since I can't reproduce this locally. Could you please share the following?

- Output of `youtui -s search beatles` and `youtui -s get-playlist VLLM`
- Screenshot of YouTube Music on your desktop showing what the page looks like when you search for Beatles

Something to try also, is the other auth method (I am assuming if you're on main or 0.0.11 you are using OAuth). Try creating a cookie.txt with the instructions from the README and run with the `-a browser` flag, e.g `youtui -a browser search beatles`.

**Comment by nick42d** [comment]
Thanks very much, I can reproduce this now.  It's the 'about these results' component that's throwing off my parser - doesn't generate for me. This will be a straightforward fix, will get right on it. 
![image](https://github.com/user-attachments/assets/4ab3c9f2-547e-49b0-b2e6-238c779d5711)

**Comment by nick42d** [comment]
RE: your question, auth method always defaults to oauth. You can override it using the cli switch or creating a `~/.config/youtui/config.toml` with the value `auth_type = "Browser"`

**Comment by nick42d** [comment]
@rkratky this should now be resolved on main. Please let me know if you experience any further issues. Regarding your question about different results from the auth types - its due to the different queries, `search` vs `search-artists`. They return different types - please see below from the library docs :)
https://docs.rs/ytmapi-rs/latest/ytmapi_rs/struct.YtMusic.html
![image](https://github.com/user-attachments/assets/046aefac-e63d-422a-855d-870390cfcf43)

**Comment by rkratky** [comment]
Yes, this seems to be fixed.
