### ISSUE TITLE
Authentication not working?

### ISSUE THREAD

**Issue by rkratky** [nick42d/youtui#169]
Attempts to play tracks always fail with 403 HTTP errors and subsequently exceeded number of allowed retries. This happens with both 'oauth' and 'browser' authentication (both freshly generated; playback in browser using the same works normally).

![image](https://github.com/user-attachments/assets/34dad566-600b-4178-9fab-bb402c03e0c8)

**Comment by nick42d** [comment]
Hey there @rkratky, thanks for all your help so far with the reports.

Unfortunately this is big problem, youtube changes [likely to curtail ad-free video downloading] have broken rusty-ytdl upstream, and I lack the expertise to resolve them myself. https://github.com/Mithronn/rusty_ytdl/issues/44

Unfortunately youtui will need to go on ice for a while until a smart cookie can figure out a workaround or Google provides an actual API like Spotify does.

I am still working on the API (which is still working), so will keep an eye on things and update this issue if I'm able to get it working again.

**Comment by nick42d** [comment]
Hopefully got a fix for this in #170.

You can now supply a poToken by adding a new file named po_token.txt in your config directory (~/.config/youtui on linux).
Information about where to get one is located here. https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide

I can't heavily support this due to lack of knowledge about the process, however it's working for now.

**Comment by rkratky** [comment]
Can confirm that this works. Thanks, @nick42d!

**Comment by nick42d** [comment]
Was closed with #170.
